Algoritmo "teste_saida"

Var
     idade : inteiro
     salario1, salario2 : real
     nome : caractere


Inicio

   escreva("Digite seu nome: ")
   leia(nome)
   escreva("Digite sua idade: ")
   leia(idade)
   escreval("Digite o quanto voce ganhou nos ultimos dois meses: ")
   leia(salario1)
   leia(salario2)
   
   escreval("DADOS DIGITADOS: ")
   escreval("Nome = ", nome)
   escreval("Salário 1: ", salario1:8:2)
   escreval("Salário 2: ", salario2:8:2)

Fimalgoritmo